import '../model/product_model.dart';

List<ProductModel> allProductList = [
// Electronics
  ProductModel(
    id: 'E001',
    name: 'Smartphone X300',
    regularPrice: 699.99,
    discountPrice: 599.99,
    status: 'Available',
    brand: 'Brand A',
    images: [
      'https://github.com/user-attachments/assets/6b5ebbd5-cb07-45f6-a86f-8ef834dfa8b4',
      'https://github.com/user-attachments/assets/3e7f3490-165c-44e4-84a9-ebeb2a90bba4',
      'https://github.com/user-attachments/assets/823b3c10-b6c3-417c-9e9e-7ca7ae40074f',
    ],
    ratings: 4.5,
    totalRatings: 150,
    description:
        'A mobile phone, or simply "mobile," is a portable communication device that allows users to make calls, send texts, and access the internet. Modern mobile phones, often referred to as smartphones, come equipped with a wide range of features such as: Mobiles have evolved to become essential tools for communication, entertainment, photography, and productivity.',
    colors: ['Red', 'Blue', 'Black'],
    sizes: ['128GB', '256GB'],
    category: 'Electronics',
  ),
  ProductModel(
    id: 'E002',
    name: 'Laptop Pro 15',
    regularPrice: 1299.99,
    discountPrice: 1099.99,
    status: 'Available',
    brand: 'Brand B',
    images: [
      'https://github.com/user-attachments/assets/1225a1e2-5cab-4d30-bd8b-a85a1b6ba11e',
      'https://github.com/user-attachments/assets/3e2859e1-3a86-498c-be0c-463e4df97e8c',
      'https://github.com/user-attachments/assets/4a1b6b49-167b-4011-b2e1-3696caa9201d',
    ],
    ratings: 4.7,
    totalRatings: 200,
    description: 'A mobile phone, or simply "mobile," is a portable communication device that allows users to make calls, send texts, and access the internet. Modern mobile phones, often referred to as smartphones, come equipped with a wide range of features such as: Mobiles have evolved to become essential tools for communication, entertainment, photography, and productivity.',
    colors: ['Red', 'Black'],
    sizes: [],
    category: 'Electronics',
  ),
  ProductModel(
    id: 'E003',
    name: 'Wireless Earbuds',
    regularPrice: 149.99,
    discountPrice: 99.99,
    status: 'Available',
    brand: 'Brand C',
    images: [
      'https://github.com/user-attachments/assets/e89fe4b8-ce9d-4269-bf67-eeead8461708',
      'https://github.com/user-attachments/assets/c218bd27-e17d-4ea8-9c4a-672183fb667a',
      'https://github.com/user-attachments/assets/35a66f7e-3ef8-491c-a435-3f23dca89b69',
    ],
    ratings: 4.2,
    totalRatings: 80,
    description:
        'A mobile phone, or simply "mobile," is a portable communication device that allows users to make calls, send texts, and access the internet. Modern mobile phones, often referred to as smartphones, come equipped with a wide range of features such as: Mobiles have evolved to become essential tools for communication, entertainment, photography, and productivity..',
    colors: ['Black', 'White'],
    sizes: [],
    category: 'Electronics',
  ),
  ProductModel(
    id: 'E004',
    name: 'Smartwatch V2',
    regularPrice: 199.99,
    discountPrice: 149.99,
    status: 'Available',
    brand: 'TechWear',
    images: [
      'https://github.com/user-attachments/assets/0170e29c-3985-4b0a-82fd-1d89b87616df',
      'https://github.com/user-attachments/assets/6ac26eb0-a821-49cd-b1e4-557263c7e8e6',
      'https://github.com/user-attachments/assets/920290ce-2580-4fb6-8c8e-1b9243955995',
    ],
    ratings: 4.6,
    totalRatings: 150,
    description: 'A mobile phone, or simply "mobile," is a portable communication device that allows users to make calls, send texts, and access the internet. Modern mobile phones, often referred to as smartphones, come equipped with a wide range of features such as: Mobiles have evolved to become essential tools for communication, entertainment, photography, and productivity.',
    colors: ['Black', 'Red'],
    sizes: [],
    category: 'Electronics',
  ),
  ProductModel(
    id: 'E005',
    name: 'Portable Bluetooth Speaker',
    regularPrice: 99.99,
    discountPrice: 69.99,
    status: 'Available',
    brand: 'SoundWave',
    images: [
      'https://github.com/user-attachments/assets/055d9309-e5ef-4356-b82b-2ca00eecd5fe',
      'https://github.com/user-attachments/assets/84f4a3ee-d8e4-4eec-8b0a-09f0881b9449',
      'https://github.com/user-attachments/assets/92608f18-1d3f-4a21-821f-bf60f09ebec4',
    ],
    ratings: 4.5,
    totalRatings: 120,
    description:
        'A mobile phone, or simply "mobile," is a portable communication device that allows users to make calls, send texts, and access the internet. Modern mobile phones, often referred to as smartphones, come equipped with a wide range of features such as: Mobiles have evolved to become essential tools for communication, entertainment, photography, and productivity.',
    colors: ['Blue', 'Black'],
    sizes: [],
    category: 'Electronics',
  ),

// Furniture
  ProductModel(
    id: 'F001',
    name: 'Luxury Leather Sofa',
    regularPrice: 999.99,
    discountPrice: 749.99,
    status: 'Available',
    brand: 'HomeStyle',
    images: [
      'https://github.com/user-attachments/assets/269ff83c-2f77-43f3-9596-86b82c3375e4',
      'https://github.com/user-attachments/assets/c9d062c2-8a4b-4241-a443-243f49654dff',
      'https://github.com/user-attachments/assets/5eeb5ed1-752f-4120-8053-7ccfaa6eb49b',
    ],
    ratings: 4.7,
    totalRatings: 85,
    description:
        'A mobile phone, or simply "mobile," is a portable communication device that allows users to make calls, send texts, and access the internet. Modern mobile phones, often referred to as smartphones, come equipped with a wide range of features such as: Mobiles have evolved to become essential tools for communication, entertainment, photography, and productivity.',
    colors: ['Black', 'Red'],
    sizes: ['3-seater', '2-seater'],
    category: 'Furniture',
  ),
  ProductModel(
    id: 'F002',
    name: 'Wooden Dining Table',
    regularPrice: 499.99,
    discountPrice: 399.99,
    status: 'Available',
    brand: 'ClassicDesign',
    images: [
      'https://github.com/user-attachments/assets/ea6f4a45-bcda-45c4-ac05-8286c57064aa',
      'https://github.com/user-attachments/assets/9565cb13-e9ca-4ee8-a9e2-017a12cb4137',
      'https://github.com/user-attachments/assets/cc6e490f-54e8-461b-9a89-dc91e1c48493',
    ],
    ratings: 4.5,
    totalRatings: 95,
    description: 'A mobile phone, or simply "mobile," is a portable communication device that allows users to make calls, send texts, and access the internet. Modern mobile phones, often referred to as smartphones, come equipped with a wide range of features such as: Mobiles have evolved to become essential tools for communication, entertainment, photography, and productivity.',
    colors: ['Red', 'Black'],
    sizes: ['4 seats', '6 seats'],
    category: 'Furniture',
  ),
  ProductModel(
    id: 'F003',
    name: 'Modern Bookshelf',
    regularPrice: 299.99,
    discountPrice: 199.99,
    status: 'Available',
    brand: 'BookWorld',
    images: [
      'https://github.com/user-attachments/assets/25f944db-399e-4942-a14b-9af64c33cdd0',
      'https://github.com/user-attachments/assets/af18ef55-a5d3-43a0-8bab-ca256cea188c',
      'https://github.com/user-attachments/assets/8af8d7e5-ce08-4063-abcd-8759cb581264',
    ],
    ratings: 4.8,
    totalRatings: 75,
    description: 'A mobile phone, or simply "mobile," is a portable communication device that allows users to make calls, send texts, and access the internet. Modern mobile phones, often referred to as smartphones, come equipped with a wide range of features such as: Mobiles have evolved to become essential tools for communication, entertainment, photography, and productivity.',
    colors: ['White', 'Black'],
    sizes: [],
    category: 'Furniture',
  ),
  ProductModel(
    id: 'F004',
    name: 'Ergonomic Office Chair',
    regularPrice: 199.99,
    discountPrice: 149.99,
    status: 'Available',
    brand: 'WorkComfort',
    images: [
      'https://github.com/user-attachments/assets/b0ebbc3e-a8d8-4da3-8fb1-d82aec483c1f',
      'https://github.com/user-attachments/assets/d40e3ca1-66d3-442c-bac4-14680474d303',
      'https://github.com/user-attachments/assets/69d78bee-9c23-401f-a8eb-c445057df5e2',
    ],
    ratings: 4.2,
    totalRatings: 60,
    description: 'A mobile phone, or simply "mobile," is a portable communication device that allows users to make calls, send texts, and access the internet. Modern mobile phones, often referred to as smartphones, come equipped with a wide range of features such as: Mobiles have evolved to become essential tools for communication, entertainment, photography, and productivity.',
    colors: ['Black', 'Red'],
    sizes: [],
    category: 'Furniture',
  ),
  ProductModel(
    id: 'F005',
    name: 'Queen Bed Frame',
    regularPrice: 399.99,
    discountPrice: 299.99,
    status: 'Available',
    brand: 'SleepWell',
    images: [
      'https://github.com/user-attachments/assets/0cf48203-c38f-482c-a416-c03641a605b3',
      'https://github.com/user-attachments/assets/170e1d2f-61ed-4b81-8d83-f7caef621134',
      'https://github.com/user-attachments/assets/eec625a4-65c3-43f9-bd6f-e53325e6dc4c',
    ],
    ratings: 4.6,
    totalRatings: 50,
    description: 'A mobile phone, or simply "mobile," is a portable communication device that allows users to make calls, send texts, and access the internet. Modern mobile phones, often referred to as smartphones, come equipped with a wide range of features such as: Mobiles have evolved to become essential tools for communication, entertainment, photography, and productivity.',
    colors: ['Red', 'White'],
    sizes: [],
    category: 'Furniture',
  ),

// Sports
  ProductModel(
    id: 'S001',
    name: 'Fitness Tracker Watch',
    regularPrice: 199.99,
    discountPrice: 149.99,
    status: 'Available',
    brand: 'FitBand',
    images: [
      'https://via.placeholder.com/150',
      'https://github.com/user-attachments/assets/8195c318-2e96-45d5-9b3a-b9039b285994',
      'https://github.com/user-attachments/assets/54b18486-d52d-4b25-8be1-3613e9e1d035',
      'https://github.com/user-attachments/assets/6b385e84-8c98-44eb-8514-e3d8bd458535',
    ],
    ratings: 4.2,
    totalRatings: 65,
    description:
        'A mobile phone, or simply "mobile," is a portable communication device that allows users to make calls, send texts, and access the internet. Modern mobile phones, often referred to as smartphones, come equipped with a wide range of features such as: Mobiles have evolved to become essential tools for communication, entertainment, photography, and productivity.',
    colors: ['Black', 'Blue'],
    sizes: [],
    category: 'Sports',
  ),
  ProductModel(
    id: 'S002',
    name: 'Yoga Mat',
    regularPrice: 39.99,
    discountPrice: 29.99,
    status: 'Available',
    brand: 'YogaPro',
    images: [
      'https://github.com/user-attachments/assets/a90a5b7a-39aa-4e16-b216-efd04ca15990',
      'https://github.com/user-attachments/assets/30de336a-d9d1-49bd-b264-e4baaeb5d58d',
      'https://github.com/user-attachments/assets/d341880d-1da8-44e7-a867-1f29c2bf95d7',
    ],
    ratings: 4.0,
    totalRatings: 100,
    description: 'High-quality yoga mat with excellent grip and comfort.A mobile phone, or simply "mobile," is a portable communication device that allows users to make calls, send texts, and access the internet. Modern mobile phones, often referred to as smartphones, come equipped with a wide range of features such as: Mobiles have evolved to become essential tools for communication, entertainment, photography, and productivity.',
    colors: ['Blue', 'Green'],
    sizes: [],
    category: 'Sports',
  ),
  ProductModel(
    id: 'S003',
    name: 'Running Shoes',
    regularPrice: 89.99,
    discountPrice: 69.99,
    status: 'Available',
    brand: 'RunFast',
    images: [
      'https://github.com/user-attachments/assets/7dd206d0-6a28-4371-9401-e858f6d1276e',
      'https://github.com/user-attachments/assets/da10be17-93bd-418d-8aae-7b87a5eb657d',
      'https://github.com/user-attachments/assets/7354867e-3425-4d38-9681-0c32de3003c9',
    ],
    ratings: 4.6,
    totalRatings: 120,
    description: 'Comfortable running shoes for all athletes.A mobile phone, or simply "mobile," is a portable communication device that allows users to make calls, send texts, and access the internet. Modern mobile phones, often referred to as smartphones, come equipped with a wide range of features such as: Mobiles have evolved to become essential tools for communication, entertainment, photography, and productivity.',
    colors: ['Blue', 'Red'],
    sizes: ['8', '9', '10', '11'],
    category: 'Sports',
  ),
  ProductModel(
    id: 'S004',
    name: 'Boxing Gloves',
    regularPrice: 59.99,
    discountPrice: 39.99,
    status: 'Available',
    brand: 'BoxingPro',
    images: [
      'https://github.com/user-attachments/assets/3234dffc-0925-4151-95c3-fb5ccdeade13',
      'https://github.com/user-attachments/assets/a1a976eb-191f-486a-b732-ec76e8a7fa16',
      'https://github.com/user-attachments/assets/56598daa-103d-4255-886f-73a84d848833',
    ],
    ratings: 4.4,
    totalRatings: 70,
    description: 'Durable boxing gloves for training and matches.A mobile phone, or simply "mobile," is a portable communication device that allows users to make calls, send texts, and access the internet. Modern mobile phones, often referred to as smartphones, come equipped with a wide range of features such as: Mobiles have evolved to become essential tools for communication, entertainment, photography, and productivity.',
    colors: ['Black', 'Red'],
    sizes: [],
    category: 'Sports',
  ),
  ProductModel(
    id: 'S005',
    name: 'Bicycle Helmet',
    regularPrice: 49.99,
    discountPrice: 39.99,
    status: 'Available',
    brand: 'CycleSafe',
    images: [
      'https://github.com/user-attachments/assets/505a72d1-bae9-4d0d-9e81-3e9a1032ace9',
      'https://github.com/user-attachments/assets/a62dc0d9-5ddd-4f40-a349-7486a0aad343',
      'https://github.com/user-attachments/assets/8ddc73ed-1f33-4413-8ee4-a363df29a846',
    ],
    ratings: 4.5,
    totalRatings: 60,
    description: 'Protect your head with this comfortable bicycle helmet.A mobile phone, or simply "mobile," is a portable communication device that allows users to make calls, send texts, and access the internet. Modern mobile phones, often referred to as smartphones, come equipped with a wide range of features such as: Mobiles have evolved to become essential tools for communication, entertainment, photography, and productivity.',
    colors: ['Yellow', 'Black'],
    sizes: [],
    category: 'Sports',
  ),

// Clothes
  ProductModel(
    id: 'C001',
    name: 'Casual T-Shirt',
    regularPrice: 29.99,
    discountPrice: 19.99,
    status: 'Available',
    brand: 'StyleWear',
    images: [
      'https://github.com/user-attachments/assets/69939873-1782-4edb-adc0-1a21418ebaeb',
      'https://github.com/user-attachments/assets/b5ff98bb-f965-45df-81c0-26e88bc4d7b9',
      'https://github.com/user-attachments/assets/cf3f0efd-7709-429c-a904-f0438ecdf630',
    ],
    ratings: 4.0,
    totalRatings: 85,
    description: 'A comfortable casual t-shirt made from soft cotton.A mobile phone, or simply "mobile," is a portable communication device that allows users to make calls, send texts, and access the internet. Modern mobile phones, often referred to as smartphones, come equipped with a wide range of features such as: Mobiles have evolved to become essential tools for communication, entertainment, photography, and productivity.',
    colors: ['Black', 'White', 'Blue'],
    sizes: ['S', 'M', 'L', 'XL'],
    category: 'Clothes',
  ),
  ProductModel(
    id: 'C002',
    name: 'Classic Blue Jeans',
    regularPrice: 49.99,
    discountPrice: 39.99,
    status: 'Available',
    brand: 'DenimBrand',
    images: [
      'https://github.com/user-attachments/assets/77146b63-8a9f-4822-8691-4ccdddeeb41a',
      'https://github.com/user-attachments/assets/affdfafc-7c7f-4cdd-ab5f-679f89700c71',
      'https://github.com/user-attachments/assets/fe47f5da-943a-48e9-adef-f638cdd96be3',
    ],
    ratings: 4.3,
    totalRatings: 75,
    description: 'Classic blue jeans that never go out of style.A mobile phone, or simply "mobile," is a portable communication device that allows users to make calls, send texts, and access the internet. Modern mobile phones, often referred to as smartphones, come equipped with a wide range of features such as: Mobiles have evolved to become essential tools for communication, entertainment, photography, and productivity.',
    colors: ['Blue', 'Black'],
    sizes: ['30', '32', '34', '36'],
    category: 'Clothes',
  ),
  ProductModel(
    id: 'C003',
    name: 'Men’s Formal Shirt',
    regularPrice: 39.99,
    discountPrice: 29.99,
    status: 'Available',
    brand: 'ElegantWear',
    images: [
      'https://github.com/user-attachments/assets/31aa0a6b-50e2-4718-97cd-50b444de43f0',
      'https://github.com/user-attachments/assets/6d6baaf6-68ee-4edc-907c-0b645a35fffe',
      'https://github.com/user-attachments/assets/b7fc60b7-add7-4142-b60b-f73dce810528',
    ],
    ratings: 4.5,
    totalRatings: 95,
    description: 'A stylish formal shirt for special occasions.A mobile phone, or simply "mobile," is a portable communication device that allows users to make calls, send texts, and access the internet. Modern mobile phones, often referred to as smartphones, come equipped with a wide range of features such as: Mobiles have evolved to become essential tools for communication, entertainment, photography, and productivity.',
    colors: ['White', 'Blue'],
    sizes: ['M', 'L', 'XL'],
    category: 'Clothes',
  ),
  ProductModel(
    id: 'C004',
    name: 'Women\'s Summer Dress',
    regularPrice: 59.99,
    discountPrice: 49.99,
    status: 'Available',
    brand: 'Fashionista',
    images: [
      'https://github.com/user-attachments/assets/4eb0e115-2a4e-4583-be76-3cba50182030',
      'https://github.com/user-attachments/assets/a3f553d6-16a3-40c6-9d02-49eae1671cb4',
      'https://github.com/user-attachments/assets/d73298a7-f2cb-45be-9298-73a813a60136',
    ],
    ratings: 4.6,
    totalRatings: 100,
    description: 'A beautiful summer dress perfect for warm days.A mobile phone, or simply "mobile," is a portable communication device that allows users to make calls, send texts, and access the internet. Modern mobile phones, often referred to as smartphones, come equipped with a wide range of features such as: Mobiles have evolved to become essential tools for communication, entertainment, photography, and productivity.',
    colors: ['Blue', 'Red'],
    sizes: ['M', 'L'],
    category: 'Clothes',
  ),
  ProductModel(
    id: 'C005',
    name: 'Winter Jacket',
    regularPrice: 89.99,
    discountPrice: 69.99,
    status: 'Available',
    brand: 'Outdoors',
    images: [
      'https://github.com/user-attachments/assets/80165e59-2acc-42e0-9461-119b65dc10bc',
      'https://github.com/user-attachments/assets/0818dd03-38af-4e4b-a9a2-d7eb99345e7c',
      'https://github.com/user-attachments/assets/f73a801f-9203-4233-aace-b76d47cb0917',
    ],
    ratings: 4.8,
    totalRatings: 50,
    description: 'Stay warm with our stylish winter jacket.A mobile phone, or simply "mobile," is a portable communication device that allows users to make calls, send texts, and access the internet. Modern mobile phones, often referred to as smartphones, come equipped with a wide range of features such as: Mobiles have evolved to become essential tools for communication, entertainment, photography, and productivity.',
    colors: ['Black', 'Red'],
    sizes: ['S', 'M', 'L', 'XL'],
    category: 'Clothes',
  ),

// Cosmetics
  ProductModel(
    id: 'COS001',
    name: 'Luxury Face Cream',
    regularPrice: 49.99,
    discountPrice: 39.99,
    status: 'Available',
    brand: 'CosmeticBrand',
    images: [
      'https://github.com/user-attachments/assets/d8101aef-1f09-4a12-b42b-0ca9c0a51923',
      'https://github.com/user-attachments/assets/11fdf8bb-e602-4791-a79a-b92d9495cd9b',
      'https://github.com/user-attachments/assets/b42fe312-2afa-45de-98d0-da1a0a33e80c',
    ],
    ratings: 4.8,
    totalRatings: 120,
    description: 'A premium face cream for healthy and radiant skin.A mobile phone, or simply "mobile," is a portable communication device that allows users to make calls, send texts, and access the internet. Modern mobile phones, often referred to as smartphones, come equipped with a wide range of features such as: Mobiles have evolved to become essential tools for communication, entertainment, photography, and productivity.',
    colors: [],
    sizes: [],
    category: 'Cosmetics',
  ),
  ProductModel(
    id: 'COS002',
    name: 'Makeup Brush Set',
    regularPrice: 39.99,
    discountPrice: 29.99,
    status: 'Available',
    brand: 'BeautyCo',
    images: [
      'https://github.com/user-attachments/assets/3273b329-ddde-474d-a666-9fc1cd7bf47a',
      'https://github.com/user-attachments/assets/af67c1d3-cf99-43e6-8168-b616efc393ba',
      'https://github.com/user-attachments/assets/f8c84728-2c2b-423c-9566-d303937930f7',
    ],
    ratings: 4.5,
    totalRatings: 110,
    description: 'Professional makeup brush set for flawless makeup.A mobile phone, or simply "mobile," is a portable communication device that allows users to make calls, send texts, and access the internet. Modern mobile phones, often referred to as smartphones, come equipped with a wide range of features such as: Mobiles have evolved to become essential tools for communication, entertainment, photography, and productivity.',
    colors: [],
    sizes: [],
    category: 'Cosmetics',
  ),
  ProductModel(
    id: 'COS003',
    name: 'Hydrating Lip Balm',
    regularPrice: 9.99,
    discountPrice: 5.99,
    status: 'Available',
    brand: 'LipCare',
    images: [
      'https://github.com/user-attachments/assets/3da4ac5d-d328-4006-aba9-c674f4ba97e0',
      'https://github.com/user-attachments/assets/cc395b3b-a07b-47e2-a909-40ca07df4376',
      'https://github.com/user-attachments/assets/b92d5af4-6d2b-45aa-8a12-eb48cce532da',
    ],
    ratings: 4.3,
    totalRatings: 95,
    description: 'Richly hydrating lip balm for soft lips.A mobile phone, or simply "mobile," is a portable communication device that allows users to make calls, send texts, and access the internet. Modern mobile phones, often referred to as smartphones, come equipped with a wide range of features such as: Mobiles have evolved to become essential tools for communication, entertainment, photography, and productivity.',
    colors: [],
    sizes: [],
    category: 'Cosmetics',
  ),
  ProductModel(
    id: 'COS003',
    name: 'Hydrating Lip Balm',
    regularPrice: 9.99,
    discountPrice: 5.99,
    status: 'Available',
    brand: 'LipCare',
    images: [
      'https://via.placeholder.com/150',
    ],
    ratings: 4.3,
    totalRatings: 95,
    description: 'Richly hydrating lip balm for soft lips.A mobile phone, or simply "mobile," is a portable communication device that allows users to make calls, send texts, and access the internet. Modern mobile phones, often referred to as smartphones, come equipped with a wide range of features such as: Mobiles have evolved to become essential tools for communication, entertainment, photography, and productivity.',
    colors: [],
    sizes: [],
    category: 'Cosmetics',
  ),
  ProductModel(
    id: 'COS003',
    name: 'Hydrating Lip Balm',
    regularPrice: 9.99,
    discountPrice: 5.99,
    status: 'Available',
    brand: 'LipCare',
    images: [
      'https://github.com/user-attachments/assets/f5728349-dbd8-4eb7-9ba7-05f571cab50e',
      'https://github.com/user-attachments/assets/b42fe312-2afa-45de-98d0-da1a0a33e80c',
      'https://github.com/user-attachments/assets/d73298a7-f2cb-45be-9298-73a813a60136',
    ],
    ratings: 4.3,
    totalRatings: 95,
    description: 'Richly hydrating lip balm for soft lips.A mobile phone, or simply "mobile," is a portable communication device that allows users to make calls, send texts, and access the internet. Modern mobile phones, often referred to as smartphones, come equipped with a wide range of features such as: Mobiles have evolved to become essential tools for communication, entertainment, photography, and productivity.',
    colors: [],
    sizes: [],
    category: 'Cosmetics',
  )
];
